[pytest]
norecursedirs =
    submission_package
filterwarnings =
    ignore:.*np.find_common_type is deprecated.*:DeprecationWarning
    ignore:.*WordPiece.__init__ will not create from files anymore.*:DeprecationWarning
    ignore:.*请将 Pandas 升级到 2.2.0 及以上版本.*:UserWarning
